networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./../src:${APP_DIR:-/var/www/html/app}
    links:
      - php-fpm
    ports:
      - "${HOST_PORT:-80}:80"
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        HOST_TZ: ${HOST_TZ:-UTC}
        WORK_DIR: ${APP_DIR:-/var/www/html/app}
        XDEBUG_INSTALL: ${XDEBUG_INSTALL:-false}
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./../src:${APP_DIR:-/var/www/html/app}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-developer}
      MYSQL_USER: ${DB_USERNAME:-developer}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - ./../data/mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT:-3306}
      UPLOAD_LIMIT: 256M
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    ports:
      - '8081:80'
    networks:
      - app-network
